"""Added promocodes

Revision ID: bd7f405436f0
Revises: 90e1d8b259ca
Create Date: 2024-03-07 22:29:49.151996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7f405436f0'
down_revision: Union[str, None] = '90e1d8b259ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('usages', sa.Integer(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promo_id'), 'promo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_id'), table_name='promo')
    op.drop_table('promo')
    # ### end Alembic commands ###
