"""Added 'popular' field to Product;

Revision ID: 7563c4b0daa8
Revises: bd7f405436f0
Create Date: 2024-07-24 21:30:07.034185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7563c4b0daa8"
down_revision: Union[str, None] = "bd7f405436f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "popular", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "popular")
    # ### end Alembic commands ###
