"""Added money field to User and custom_command to Product

Revision ID: 7b6e34392f03
Revises: 7563c4b0daa8
Create Date: 2024-07-26 16:55:23.356092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7b6e34392f03"
down_revision: Union[str, None] = "7563c4b0daa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product", sa.Column("custom_command", sa.String(), nullable=False))
    op.add_column(
        "user", sa.Column("money", sa.Integer(), server_default="0", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "money")
    op.drop_column("product", "custom_command")
    # ### end Alembic commands ###
