"""Added extra id to Form.

Revision ID: 90e1d8b259ca
Revises: 86f3aa28a61f
Create Date: 2024-01-18 16:51:55.231265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90e1d8b259ca"
down_revision: Union[str, None] = "86f3aa28a61f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("form", sa.Column("extra_id", sa.String(), nullable=False))
    op.create_unique_constraint(None, "form", ["extra_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "form", type_="unique")
    op.drop_column("form", "extra_id")
    # ### end Alembic commands ###
