from os import environ

from dotenv import load_dotenv

load_dotenv(".env" if not environ.get("DEV") else ".env.dev")

BOT_TOKEN = environ["BOT_TOKEN"]
CLIENT_SECRET = environ["CLIENT_SECRET"]
CLIENT_ID = environ["CLIENT_ID"]
DISCORD_API_ENDPOINT = "https://discord.com/api/v10"
BASE_URI = environ["BASE_URI"]
REDIRECT_URI = f"{BASE_URI}api/v1/discord/callback"

DISCORD_GUILD_ID = "1075421019084443709"
DISCORD_ADMIN_ROLE_ID = "1132667490791591946"
DISCORD_MODERATOR_ROLE_ID = "1161345611208069150"

MAIN_MC_SERVER_HOST = environ["MAIN_MC_SERVER_HOST"]
SECOND_MC_SERVER_HOST = environ["SECOND_MC_SERVER_HOST"]
MC_SERVER_KEY = environ["MC_SERVER_KEY"]

ADMINS = ["493318176189448204"]

ENOT_API_KEY = environ["ENOT_API_KEY"]
ENOT_API_SIGNATURE = environ["ENOT_API_SIGNATURE"]
SHOP_ID = environ["SHOP_ID"]
SHOP_NUM_ID = environ["SHOP_NUM_ID"]
DATABASE_CONNECTION = environ["DATABASE_CONNECTION"]
