from os import environ

BOT_TOKEN = environ["BOT_TOKEN"]
CLIENT_SECRET = environ["CLIENT_SECRET"]
CLIENT_ID = environ["CLIENT_ID"]
DISCORD_API_ENDPOINT = environ["DISCORD_API_ENDPOINT"]
REDIRECT_URI = environ["REDIRECT_URI"]
BASE_URI = environ["BASE_URI"]
ADMIN_PASSWORD = environ["ADMIN_PASSWORD"]
SECRET_KEY = environ["SECRET_KEY"]
