from os import environ

BOT_TOKEN = environ["BOT_TOKEN"]
CLIENT_SECRET = environ["CLIENT_SECRET"]
CLIENT_ID = environ["CLIENT_ID"]
DISCORD_API_ENDPOINT = environ["DISCORD_API_ENDPOINT"]
REDIRECT_URI = environ["REDIRECT_URI"]
BASE_URI = environ["BASE_URI"]

DISCORD_GUILD_ID = environ["DISCORD_GUILD_ID"]
DISCORD_ADMIN_ROLE_ID = environ["DISCORD_ADMIN_ROLE_ID"]
DISCORD_MODERATOR_ROLE_ID = environ["DISCORD_MODERATOR_ROLE_ID"]

MAIN_MC_SERVER_HOST = environ["MAIN_MC_SERVER_HOST"]
SECOND_MC_SERVER_HOST = environ["SECOND_MC_SERVER_HOST"]
MC_SERVER_KEY = environ["MC_SERVER_KEY"]

ADMINS = ["493318176189448204"]

ENOT_API_KEY = environ["ENOT_API_KEY"]
ENOT_API_SIGNATURE = environ["ENOT_API_SIGNATURE"]
SHOP_ID = environ["SHOP_ID"]
SHOP_NUM_ID = environ["SHOP_NUM_ID"]
